// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lievuqelejdfxeyatalw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpZXZ1cWVsZWpkZnhleWF0YWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MjIwMDEsImV4cCI6MjA1Nzk5ODAwMX0.s9FZqVsgNz1oItGzL5_SKOW1otp9SzUwte7iPdTH4Q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);